import mongoose from "mongoose";

const EmployeeSkillSchema = new mongoose.Schema(
  {
    shift: {
      type: [String],
      enum: ["Breakfast", "Lunch", "Dinner"],
    },
    primaryJob: {
      title: {
        type: String,
        enum: [
          "Regional Manager",
          "Director of Ops",
          "Director of F&B",
          "General Manager",
          "Executive Chef",
          "Kitchen Manager",
          "Sous Chef",
          "Pastry Chef",
          "Banquet Chef",
          "Manager",
          "Sales Manager",
          "Supervisor",
          "Banquet Captain",
          "Line Cook",
          "Pastry Cook",
          "Expeditor",
          "Food Runner",
          "Bartender",
          "Barback",
          "Food Server",
          "Counter Server",
          "Server Assitant",
          "Banquet Server",
          "Banquet Bartender",
          "Hostess",
          "Dishwasher",
          "Barista",
          "Expeditor",
          "Fastfood Cook",
          "Bar Manager",
          "Lead Bartender",
          "Fastfood Server",
          "Host/Hostess",
          "Valet",
          "Casher",
          "Bar Manager",
          "Chef De Cuisine",
          "Grill Cook",
          "Saute Cook",
          "Fry Cook",
          "Pantry Cook",
          "",
        ],
      },
      years: Number,
    },
    secondaryJob: [
      //*** should valid max 3 array */
      {
        title: {
          type: String,
          enum: [
            "Regional Manager",
            "Director of Ops",
            "Director of F&B",
            "General Manager",
            "Executive Chef",
            "Kitchen Manager",
            "Sous Chef",
            "Pastry Chef",
            "Banquet Chef",
            "Manager",
            "Sales Manager",
            "Supervisor",
            "Banquet Captain",
            "Line Cook",
            "Pastry Cook",
            "Expeditor",
            "Food Runner",
            "Bartender",
            "Barback",
            "Food Server",
            "Counter Server",
            "Server Assitant",
            "Banquet Server",
            "Banquet Bartender",
            "Hostess",
            "Dishwasher",
            "Barista",
            "Expeditor",
            "Fastfood Cook",
            "Bar Manager",
            "Lead Bartender",
            "Fastfood Server",
            "Host/Hostess",
            "Valet",
            "Casher",
            "Bar Manager",
            "Chef De Cuisine",
            "Grill Cook",
            "Saute Cook",
            "Fry Cook",
            "Pantry Cook",
            "",
          ],
        },
        years: Number,
      },
    ],
    style: [
      {
        type: {
          type: String,
          enum: [
            "Fast Food",
            "Banquet",
            "Counter Service",
            "Full-Service Casual",
            "Upscale Casual",
            "Fine Dining",
            "",
          ],
        },
        years: Number,
      },
    ],
    styleCurrent: String,
    cuisine: [
      //*** should valid max 4 array */
      {
        type: {
          type: String,
          enum: [
            "Seafood",
            "Steakhouse",
            "Pizza",
            "American",
            "Chinese",
            "Thai",
            "Japanese",
            "Kosher",
            "BBQ",
            "Sandwiches",
            "Coffee Shop",
            "Cuban",
            "Caribbean",
            "Greek",
            "Brazilian",
            "French",
            "Italian",
            "Fondue",
            "Middle Eastern",
            "Vegan/Vegetarian",
            "Sushi",
            "Mexican",
            "Fastfood",
            "Bagels",
            "Buffet",
            "Brunch/Breakfast",
            "Fastfood Burgers",
            "Cafe",
            "",
          ],
        },
        years: Number,
      },
    ],
    wineKnowledge: {
      type: String,
      enum: ["Barefoot", "Sutterhome", "Silver Oak", "Chat.Margaux", ""],
    },
    cocktailKnowledge: {
      type: String,
      enum: ["White Claw", "Jack & Coke", "Old Fashioned", "Sazerac", ""],
    },
    // POS and Reservation systems
    systems: [String],
    createdAt: {
      type: Date,
      default: Date.now,
    },
    updatedAt: {
      type: Date,
    },
    employee: {
      type: mongoose.Schema.ObjectId,
      ref: "Employee",
      required: true,
    },
  },
  {
    // set virtuals - employee
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

export default mongoose.model("EmployeeSkill", EmployeeSkillSchema);
