//// ** Types for employee to register profession ** ////

//export const jobs = ['primaryJob', 'secondaryJob'];
export const jobTypes = [
  'Director of Ops',
  'General Manager',
  'Executive Chef',
  'Sous Chef',
  'Pastry Chef',
  'Banquet Chef',
  'Manager',
  'Supervisor',
  'Banquet Captain',
  'Line Cook',
  'Pastry Cook',
  'Expediter',
  'Food Runner',
  'Bartender',
  'Barback',
  'Food Server',
  'Counter Server',
  'Server Assitant',
  'Banquet Server',
  'Banquet Bartender',
  'Hostess',
  'Dishwasher',
  'Barista',
  'Fastfood Cook',
  'Fastfood Server',
  'Velet',
  'Casher',
  'Hotel Front Desk',
  'Sales Manager',
  'Hotel Outlet Staff',
  'Hotel Bellman',
  'Pool Attendant',
];

export const shifts = ['Breakfast', 'Lunch', 'Dinner'];

export const shiftst = [
  { id: 'breakfast', value: 'Breakfast' },
  { id: 'lunch', value: 'Lunch' },
  { id: 'dinner', value: 'Dinner' },
];

export const styles = [
  'Fast Food',
  'Banquet',
  'Counter Service',
  'Full-Service Casual',
  'Upscale Casual',
  'Fine Dining',
];

export const cuisines = [
  'Seafood',
  'Steakhouse',
  'Pizza',
  'American',
  'Chinese',
  'Thai',
  'Japanese',
  'Kosher',
  'BBQ',
  'Sandwiches',
  'Coffee Shop',
  'Cuban',
  'Caribbean',
  'Greek',
  'Brazilian',
  'French',
  'Italian',
  'Fondue',
  'Middle Eastern',
  'Vegan/Vegetarian',
  'Sushi',
  'Deli',
  'Fastfood',
  'Bagels',
  'Buffet',
  'Brunch/Breakfast',
  'Fastfood Burgers',
  'Cafe',
];

export const wineKnowledges = [
  'Barefoot',
  'Sutterhome',
  'Silver Oak',
  'Chat.Margaux',
];

export const cocktailKnowledges = [
  'White Claw',
  'Jack & Coke',
  'Old Fashioned',
  'Sazerac',
];

export const poss = [
  'Harbortouch',
  'Square for Restaurants',
  'TouchBistro',
  'ShopKeep',
  'Rezku POS',
  'Cake POS',
  'Toast POS',
  'Upserve',
  'SpotOn Restaurants',
  'Lightspeed Restaurant',
  'Clover',
  'Loyverse',
  'EPOS Now',
  'Nobly POS',
  'Aloha POS',
  'Revel Systems',
  'EZee BurrP',
  'Positouch',
  'BrewPOS',
  'NCR Silver',
  'Future POS',
  'Maitre’D',
  'Aldelo POS',
  'Restaurant Manager POS',
  'Lavu POS',
  'AccuPOS',
  'Micros',
  'Squirrel',
  'Talech',
  'FusionResto',
  'Thrive',
];

export const reservations = [
  'Open Table',
  'No Wait/Yelp',
  'Tablein',
  'Eveve',
  'Tableagent',
  'Resy',
  'Tock',
  'Reserve',
  'Wisely',
  'Bookatable',
  'Sevenrooms',
  'BentoBox',
  'Hostme',
  'ResDiary',
];

export const systems = [
  'Harbortouch',
  'Square for Restaurants',
  'TouchBistro',
  'ShopKeep',
  'Rezku POS',
  'Cake POS',
  'Toast POS',
  'Upserve',
  'SpotOn Restaurants',
  'Lightspeed Restaurant',
  'Clover',
  'Loyverse',
  'EPOS Now',
  'Nobly POS',
  'Aloha POS',
  'Revel Systems',
  'EZee BurrP',
  'Positouch',
  'BrewPOS',
  'NCR Silver',
  'Future POS',
  'Maitre’D',
  'Aldelo POS',
  'Restaurant Manager POS',
  'Lavu POS',
  'AccuPOS',
  'Micros',
  'Squirrel',
  'Talech',
  'FusionResto',
  'Thrive',
  'Open Table',
  'No Wait/Yelp',
  'Tablein',
  'Eveve',
  'Tableagent',
  'Resy',
  'Tock',
  'Reserve',
  'Wisely',
  'Bookatable',
  'Sevenrooms',
  'BentoBox',
  'Hostme',
  'ResDiary',
];

export const roles = [
  'Line Cook AM',
  'Line Cook PM',
  'Pastry Cook',
  'Breakfast Cook',
  'Banquet Cook',
  'Grill Cook',
  'Bartender',
  'Banquet Bartender',
  'Barback',
  'Full-Service Server',
  'Food-Server-Counter',
  'Banquet Server',
  'Server Assitant',
  'Hostess',
  'Dishwasher',
  'Barista',
  'Valet',
];

export const usaStates = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'DC', label: 'District Of Columbia' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
];
